--------------------------------------------------------
-- Archivo creado  - domingo-marzo-18-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DETALLEPEDIDO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DETALLEPEDIDO" 
   (	"IDPEDIDO" NUMBER, 
	"IDARTICULO" NUMBER, 
	"VALORARTICULO" NUMBER, 
	"TALLASELECCIONADA" VARCHAR2(20 BYTE), 
	"COLORSELECCIONADO" VARCHAR2(20 BYTE), 
	"CANTIDAD" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.DETALLEPEDIDO
SET DEFINE OFF;
